---
title: "Preprocessing 000012056303"
author: "Niklas Rindtorff"
date: "1/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dcphelper)
```

# Brightfield Flatfield projection
## Naming target dir 

```{r}
new_path_base = "/home/ubuntu/bucket/metadata/000012056303__2018-11-18T10_49_08-Measurement_1/"
new_json_path_flat = "/home/ubuntu/bucket/metadata/job_flatfield_template.json"
new_json_path_max = "/home/ubuntu/bucket/metadata/job_maxproj_template.json"
```

## Creating target dir 

```{r}
dir.create(new_path_base) # Do not execute this from a local machine if you expect other AWS services to access the directory later on
```

## Name channels

```{r}
channel_v <- c("ch2", "ch3", "ch4")
channel_n <- c("bf", "ce", "tm")
```


## Defining metadata

```{r, eval = TRUE}
for(i in 1:length(channel_n)){
metadata_split_path <- create_flatfield_metadata_split(
  path = "/home/ubuntu/bucket/inbox/000012056303__2018-11-18T10_49_08-Measurement_1/Images/",
  channel_of_interest = channel_v[i], #brightfield
  name = channel_n[i],
  json_path = new_json_path,
  path_base = new_path_base)
}
```


## Grouping metadata

```{python, eval = TRUE}
python /home/ubuntu/bucket/metadata/ManualMetadata_dir.py ~/bucket/metadata/000012056303__2018-11-18T10_49_08-Measurement_1/ "['Metadata_parent','Metadata_timepoint', 'Metadata_well', 'Metadata_fld', 'Metadata_channel']" "bf"

python /home/ubuntu/bucket/metadata/ManualMetadata_dir.py ~/bucket/metadata/000012056303__2018-11-18T10_49_08-Measurement_1/ "['Metadata_parent','Metadata_timepoint', 'Metadata_well', 'Metadata_fld', 'Metadata_channel']" "ce"

python /home/ubuntu/bucket/metadata/ManualMetadata_dir.py ~/bucket/metadata/000012056303__2018-11-18T10_49_08-Measurement_1/ "['Metadata_parent','Metadata_timepoint', 'Metadata_well', 'Metadata_fld', 'Metadata_channel']" "tm"
```

```{r, eval = FALSE}
tmp <- paste0("python /home/ubuntu/bucket/metadata/ManualMetadata_dir.py ~/bucket/metadata/000012056303__2018-11-18T10_49_08-Measurement_1/ " ,'"[\'Metadata_parent\',\'Metadata_timepoint\', \'Metadata_well\', \'Metadata_fld\', \'Metadata_channel\']"', '"bf"')

system(tmp)
```


## Writing job files

```{r}
for(i in 1:length(channel_n)){
link_json_metadata(metadata_split_path = list.files(new_path_base, pattern = "metadata_", full.names = TRUE) %>%
                     stringr::str_subset(pattern = ".csv") %>%
                     stringr::str_subset(pattern = channel_n[i]), 
                   json_path = new_json_path_flat, 
                   path_base = new_path_base)
}
```

## Grouping job files and creating an executable

```{r, eval = FALSE}
for(i in 1:length(channel_n)){
group_jobs_bash(path_base = new_path_base,
                name = channel_n[i],
                letter_row_interval = c(1:3),
                number_col_interval = c(1:24))
}
```

