#!/bin/sh

# recovering files for re-analysis
# Currently I hardcoded both variables - needs work #TODO
# first arg: barcode regex
# second arg: 'ascstore'

for x in `awk '/rapid\\/cellprofiler*/' glacier-restore.txt`
  do
    echo "Begin restoring $x"
    aws s3api restore-object --restore-request '{"Days":25,"GlacierJobParameters":{"Tier":"Bulk"}}' --bucket ascstore --key "$x"
    echo "Done restoring $x"
  done
